package com.bpraak.song.ringtone.love.status.musics.util;


import com.bpraak.song.ringtone.love.status.musics.R;

public final class Const {
    public static final String[] Songname = new String[]{
            "Filhaal",
            "Teri Mitti Tribute",
            "Sach Keh Raha Hai Deewana",
            "Menu Puch Na Koi Sawal",
            "Qismat Badaldi Vekhi Main",
            "Teri Mitti Me Mil Jawa",
            "Ye Dooriya",
            "Teri Mitti Music",
            "Tera Hasna Bhi Jannat Hai",
            "Ye Jism Hai To Kya",
            "Manna Dil Da Hi Mera Kasoor",
            "Kese Fardi",
            "Maaf Kar De Mainu",
            "Har Mulaqaat",
            "Barish Ka Mausam Hu",
            "Dil Tod Ke Dialogue",
            "Tere Utte Marde",
            "Shukriya",
            "Ruthe Ruthe Se Sabere",
            "Mujhse Kuch Teri Nazar Pooch",
            "Masstaani",
            "Tumne Sudhara Tha",
            "Teri Khaamiyan",
            "Tauba Tauba",
            "Vo Tum Hi Thi",
            "Allah Di Kasam",
            "Tu Mainu Chodiyo Na",
            "Dilbara",
            "BGM",
            "Ho Sarheya",
            "Dance Like",
            "Jane Vale",
            "Koi Fariyaad",
            "Maine Pata Hai",
            "Channa Ve",
            "Mainu Lageya",
            "Duniya Di Parwaha Main Kardi Nahi",
            "Kya Jajbato Nu Bayan Kare",
            "Shukriya Shukriya",
            "Teri Aankhiya Sa Noor Kinna Sara",
            "Tum De Rahi Ho Dil Me",
            "Violiin",
            "Zindgi Me Koyi Aaye Na Rabba",
            "Ammi",
            "Bewafaai",
            "Fitoor",
            "Koun Hoyega",
            "Galib",
            "Kyon",
            "Mere Dil De Tukde",
            "Mastani",
            "Mann Bharrya",
            "Pyaar De",
            "Rabba Ve",
            "Tera Fikar Rhe Menu",
            "Qubool A",
            "Tere Husan Di Charcha Honi",
            "Zindagi",
            "Nain Tere",
            "Mera Dil",
            "Jaani",
            "Kaun Hoyega",
            "Dholna",
            "Ek Tara Kismat Da",
              };

    public static Integer[] songidlist = new Integer[]{
            R.raw.a1,
            R.raw.a2,
            R.raw.a3,
            R.raw.a4,
            R.raw.a5,
            R.raw.a6,
            R.raw.a7,
            R.raw.a8,
            R.raw.a9,
            R.raw.a10,
            R.raw.a11,
            R.raw.a12,
            R.raw.a13,
            R.raw.a14,
            R.raw.a15,
            R.raw.a16,
            R.raw.a17,
            R.raw.a18,
            R.raw.a19,
            R.raw.a20,
            R.raw.a21,
            R.raw.a22,
            R.raw.a23,
            R.raw.a24,
            R.raw.a25,
            R.raw.a26,
            R.raw.a27,
            R.raw.a28,
            R.raw.a29,
            R.raw.a30,
            R.raw.a31,
            R.raw.a32,
            R.raw.a33,
            R.raw.a34,
            R.raw.a35,
            R.raw.a36,
            R.raw.a37,
            R.raw.a38,
            R.raw.a39,
            R.raw.a40,
            R.raw.a41,
            R.raw.a42,
            R.raw.a43,
            R.raw.a44,
            R.raw.a45,
            R.raw.a46,
            R.raw.a47,
            R.raw.a48,
            R.raw.a49,
            R.raw.a50,
            R.raw.a51,
            R.raw.a52,
            R.raw.a53,
            R.raw.a54,
            R.raw.a55,
            R.raw.a56,
            R.raw.a57,
            R.raw.a58,
            R.raw.a59,
            R.raw.a60,
            R.raw.a61,
            R.raw.a62,
            R.raw.a63,
            R.raw.a64,
    };

    public static Integer[] galleryList = new Integer[]{
            R.drawable.a1,
            R.drawable.a2,
            R.drawable.a3,
            R.drawable.a4,
            R.drawable.a5,
            R.drawable.a6,
            R.drawable.a7,
            R.drawable.a8,
            R.drawable.a9,
            R.drawable.a10,
            R.drawable.a11,
            R.drawable.a12,
            R.drawable.a13,
            R.drawable.a14,
            R.drawable.a15,
            R.drawable.a16,
            R.drawable.a17,
            R.drawable.a18,
            R.drawable.a1,
            R.drawable.a2,
            R.drawable.a3,
            R.drawable.a4,
            R.drawable.a5,
            R.drawable.a6,
            R.drawable.a7,
            R.drawable.a8,
            R.drawable.a9,
            R.drawable.a10,
            R.drawable.a11,
            R.drawable.a12,
            R.drawable.a13,
            R.drawable.a14,
            R.drawable.a15,
            R.drawable.a16,
            R.drawable.a17,
            R.drawable.a18,
            R.drawable.a1,
            R.drawable.a2,
            R.drawable.a3,
            R.drawable.a4,
            R.drawable.a5,
            R.drawable.a6,
            R.drawable.a7,
            R.drawable.a8,
            R.drawable.a9,
            R.drawable.a10,
            R.drawable.a11,
            R.drawable.a12,
            R.drawable.a13,
            R.drawable.a14,
            R.drawable.a15,
            R.drawable.a16,
            R.drawable.a17,
            R.drawable.a18,
            R.drawable.a1,
            R.drawable.a2,
            R.drawable.a3,
            R.drawable.a4,
            R.drawable.a5,
            R.drawable.a6,
            R.drawable.a7,
            R.drawable.a8,
            R.drawable.a9,
            R.drawable.a10,

    };
}
